### ISSUE TITLE
MP9-N base is set to arc9_eft_mp9 instead of arc9_base

### ISSUE THREAD

**Issue by FEXlol** [dar-su/arc9_eft_mp9_mp7#1]

**Comment by dar-su** [comment]
because it based on mp9?? same as avt based on svt, pb on pm, mp7a2 on a1 and others
same as mw or csgo guns use subbases and not arc9 as base

make your dumb addon use weapons.IsBasedOn("arc9_eft_mp9n", "arc9_base") instead of direct check of variable

**Comment by FEXlol** [comment]
ok!!!!!
